spring.application.name=poll-server
spring.data.mongodb.uri=mongodb+srv://janisarakhtar392:Akhtar92@cluster0.wtqzv0w.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=pollapp
server.port=8080